### ISSUE TITLE
TODO's to be solved before publishing

### ISSUE THREAD

**Issue by crispy-coding** [crispy-coding/code-examples-web-ide#1]
- [x] I would also like Spring Server, for example, to open a port that is accessible via the browser. For this I would have to use the docker host network. The services should not be accessible from the LAN.
 - [x] Add nmap and net-tools to the tool box.
 - [x] Add Copyright information to `src/init` file as I took it from the original code-server project.
